# Lab | Pandas

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

The data includes information such as customer ID, state, gender, education, income, and other variables that can be used to perform various analyses.

Throughout the lab, we will be using the pandas library in Python to manipulate and analyze the data. Pandas is a powerful library that provides various data manipulation and analysis tools, including the ability to load and manipulate data from a variety of sources, including CSV files.

### Data Description

- Customer - Customer ID

- ST - State where customers live

- Gender - Gender of the customer

- Education - Background education of customers 

- Customer Lifetime Value - Customer lifetime value(CLV) is the total revenue the client will derive from their entire relationship with a customer. In other words, is the predicted or calculated value of a customer over their entire duration as a policyholder with the insurance company. It is an estimation of the net profit that the insurance company expects to generate from a customer throughout their relationship with the company. Customer Lifetime Value takes into account factors such as the duration of the customer's policy, premium payments, claim history, renewal likelihood, and potential additional services or products the customer may purchase. It helps insurers assess the long-term profitability and value associated with retaining a particular customer.

- Income - Customers income

- Monthly Premium Auto - Amount of money the customer pays on a monthly basis as a premium for their auto insurance coverage. It represents the recurring cost that the insured person must pay to maintain their insurance policy and receive coverage for potential damages, accidents, or other covered events related to their vehicle.

- Number of Open Complaints - Number of complaints the customer opened

- Policy Type - There are three type of policies in car insurance (Corporate Auto, Personal Auto, and Special Auto)

- Vehicle Class - Type of vehicle classes that customers have Two-Door Car, Four-Door Car SUV, Luxury SUV, Sports Car, and Luxury Car

- Total Claim Amount - the sum of all claims made by the customer. It represents the total monetary value of all approved claims for incidents such as accidents, theft, vandalism, or other covered events.

External Resources: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

## Challenge 1: Understanding the data

In this challenge, you will use pandas to explore a given dataset. Your task is to gain a deep understanding of the data by analyzing its characteristics, dimensions, and statistical properties.

- Identify the dimensions of the dataset by determining the number of rows and columns it contains.
- Determine the data types of each column and evaluate whether they are appropriate for the nature of the variable. You should also provide suggestions for fixing any incorrect data types.
- Identify the number of unique values for each column and determine which columns appear to be categorical. You should also describe the unique values of each categorical column and the range of values for numerical columns, and give your insights.
- Compute summary statistics such as mean, median, mode, standard deviation, and quartiles to understand the central tendency and distribution of the data for numerical columns. You should also provide your conclusions based on these summary statistics.
- Compute summary statistics for categorical columns and providing your conclusions based on these statistics.

In [1]:
Url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"

In [ ]:
import pandas as pd #importing the pandas library
dataframe = pd.read_csv(Url)

In [52]:
dataframe.head(20) # checking the first 5 rows of the dataframe and also to know the column names.

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
5,OC83172,Oregon,F,Bachelor,825629.78%,62902.0,69.0,1/0/00,Personal Auto,Two-Door Car,159.383042
6,XZ87318,Oregon,F,College,538089.86%,55350.0,67.0,1/0/00,Corporate Auto,Four-Door Car,321.600000
7,CF85061,Arizona,M,Master,721610.03%,0.0,101.0,1/0/00,Corporate Auto,Four-Door Car,363.029680
8,DY87989,Oregon,M,Bachelor,2412750.40%,14072.0,71.0,1/0/00,Corporate Auto,Four-Door Car,511.200000
9,BQ94931,Oregon,F,College,738817.81%,28812.0,93.0,1/0/00,Special Auto,Four-Door Car,425.527834
10,SX51350,California,M,College,473899.20%,0.0,67.0,1/0/00,Personal Auto,Four-Door Car,482.400000
11,VQ65197,California,NaN,College,819719.71%,0.0,110.0,1/0/00,Personal Auto,SUV,528.000000
12,DP39365,California,NaN,Master,879879.70%,77026.0,110.0,1/2/00,Corporate Auto,Four-Door Car,472.029737
13,SJ95423,Arizona,NaN,High School or Below,881901.89%,99845.0,110.0,1/1/00,Corporate Auto,SUV,528.000000
14,IL66569,California,NaN,College,538443.17%,83689.0,70.0,1/2/00,Corporate Auto,Four-Door Car,307.139132
15,BW63560,Oregon,NaN,Bachelor,746313.94%,24599.0,64.0,1/1/00,Corporate Auto,Four-Door Car,42.920271
16,FV94802,Nevada,NaN,High School or Below,256686.78%,25049.0,67.0,1/0/00,Personal Auto,Two-Door Car,454.245098
17,OE15005,Cali,NaN,College,394524.16%,28855.0,101.0,1/0/00,Personal Auto,SUV,647.442031
18,WC83389,Oregon,NaN,College,571033.31%,51148.0,72.0,1/0/00,Personal Auto,Four-Door Car,308.981664
19,FL50705,California,NaN,High School or Below,816261.71%,66140.0,101.0,1/0/00,Corporate Auto,Four-Door Car,484.800000

In [27]:
datatype = dataframe.dtypes
print(datatype)

Customer                         str
ST                               str
GENDER                           str
Education                        str
Customer Lifetime Value          str
Income                       float64
Monthly Premium Auto         float64
Number of Open Complaints        str
Policy Type                      str
Vehicle Class                    str
Total Claim Amount           float64
dtype: object

In [ ]:
dataframe.info() # checking the information of the dataframe to know if there are any null values in the dataframe and also to know the dtypes of the columns.
                # From the information below, under customer lifetime value, since the values there are in the form of numbers, they are to be treated as float values. However, they are being stored as string objects. This needs to be corrected by changing from string to a float and also since the percentage sign is there, it shows that the values are likely to be divided by 100.
                # Again, under the number of open complaints, it is stored as a string which per the description it needs to be stored as an integer. The only problem is that we have to understand what the structure in the number of open complaints column means since it is in three parts.

<class 'pandas.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   1071 non-null   str
 1   ST                         1071 non-null   str
 2   GENDER                     954 non-null    str
 3   Education                  1071 non-null   str
 4   Customer Lifetime Value    1068 non-null   str
 5   Income                     1071 non-null   float64
 6   Monthly Premium Auto       1071 non-null   float64
 7   Number of Open Complaints  1071 non-null   str
 8   Policy Type                1071 non-null   str
 9   Vehicle Class              1071 non-null   str
 10  Total Claim Amount         1071 non-null   float64
dtypes: float64(3), str(8)
memory usage: 417.4 KB

In [ ]:
dimension = dataframe.shape # dimension of the dataframe thus the number of rows and columns in the dataframe
print(dimension)

(4008, 11)

In [10]:
columns =dataframe.columns #the columns of the dataframe with its dtypes
print(columns)

Index(['Customer', 'ST', 'GENDER', 'Education', 'Customer Lifetime Value',
       'Income', 'Monthly Premium Auto', 'Number of Open Complaints',
       'Policy Type', 'Vehicle Class', 'Total Claim Amount'],
      dtype='str')

In [114]:
dataframe[['Customer', 'ST', 'GENDER', 'Education', 'Customer Lifetime Value',
       'Income', 'Monthly Premium Auto', 'Number of Open Complaints',
       'Policy Type', 'Vehicle Class', 'Total Claim Amount']].nunique()

Customer                     1071
ST                              8
GENDER                          5
Education                       6
Customer Lifetime Value      1027
Income                        774
Monthly Premium Auto          132
Number of Open Complaints       6
Policy Type                     3
Vehicle Class                   6
Total Claim Amount            761
dtype: int64

In [ ]:
for column in columns:      # Another option is that I used the for loop to iterate through the columns of the dataframe so that we will know the total number of unique values or categories in each column.
    print(column)
    print(dataframe[column].nunique())

Customer
1071
ST
8
GENDER
5
Education
6
Customer Lifetime Value
1027
Income
774
Monthly Premium Auto
132
Number of Open Complaints
6
Policy Type
3
Vehicle Class
6
Total Claim Amount
761

In [ ]:
categorical_columns = dataframe[["ST", "GENDER", "Education", "Policy Type", "Vehicle Class"]] # these columns are selected because they are categorical especially when you go through the values in the dataframe. In their columns, it is realised that there are similar values which can be grouped into one category.
display(categorical_columns)

              ST GENDER             Education     Policy Type  Vehicle Class
0     Washington    NaN                Master   Personal Auto  Four-Door Car
1        Arizona      F              Bachelor   Personal Auto  Four-Door Car
2         Nevada      F              Bachelor   Personal Auto   Two-Door Car
3     California      M              Bachelor  Corporate Auto            SUV
4     Washington      M  High School or Below   Personal Auto  Four-Door Car
...          ...    ...                   ...             ...            ...
4003         NaN    NaN                   NaN             NaN            NaN
4004         NaN    NaN                   NaN             NaN            NaN
4005         NaN    NaN                   NaN             NaN            NaN
4006         NaN    NaN                   NaN             NaN            NaN
4007         NaN    NaN                   NaN             NaN            NaN

[4008 rows x 5 columns]

Values in each categorical columns

In [51]:
for column in categorical_columns:
    print(column)
    print(categorical_columns[column].nunique())

ST
8
GENDER
5
Education
6
Policy Type
3
Vehicle Class
6

In [ ]:
categorical_columns["GENDER"].value_counts() # with this, i wanted to know why the gender category has a total of 5 instead of 2. This therefore needs to be standardised to have only 2 since
                                                # are small letters and capital as well

GENDER
F         457
M         413
Male       39
female     28
Femal      17
Name: count, dtype: int64

Range of Values for numerical values

In [57]:
numerical_columns = dataframe[[ "Income", "Monthly Premium Auto", "Total Claim Amount"]] # with this, the customer lifetime value column needs to be changed into float instead of string as well as the number of open complaints column.
display(numerical_columns)

       Income  Monthly Premium Auto  Total Claim Amount
0         0.0                1000.0            2.704934
1         0.0                  94.0         1131.464935
2     48767.0                 108.0          566.472247
3         0.0                 106.0          529.881344
4     36357.0                  68.0           17.269323
...       ...                   ...                 ...
4003      NaN                   NaN                 NaN
4004      NaN                   NaN                 NaN
4005      NaN                   NaN                 NaN
4006      NaN                   NaN                 NaN
4007      NaN                   NaN                 NaN

[4008 rows x 3 columns]

range of values

In [60]:
numerical_min = numerical_columns[["Income", "Monthly Premium Auto", "Total Claim Amount"]].min()
print (numerical_min)

Income                   0.000000
Monthly Premium Auto    61.000000
Total Claim Amount       0.382107
dtype: float64

In [61]:
numerical_max = numerical_columns[["Income", "Monthly Premium Auto", "Total Claim Amount"]].max()
print (numerical_max)

Income                  99960.000000
Monthly Premium Auto    35354.000000
Total Claim Amount       2893.239678
dtype: float64

the range between the numerical columns is that the minimum value ranges from 0 - 61 and the maximum values ranges from 2893.24 - 99960.

In [66]:
numerical_mean = numerical_columns[["Income", "Monthly Premium Auto", "Total Claim Amount"]].mean()
print (numerical_mean)

Income                  39295.701214
Monthly Premium Auto      193.234360
Total Claim Amount        404.986909
dtype: float64

In [63]:
numerical_median = numerical_columns[["Income", "Monthly Premium Auto", "Total Claim Amount"]].median()
print (numerical_median)

Income                  36234.000000
Monthly Premium Auto       83.000000
Total Claim Amount        354.729129
dtype: float64

In [65]:
numerical_description = numerical_columns[["Income", "Monthly Premium Auto", "Total Claim Amount"]].describe()
display (numerical_description)

             Income  Monthly Premium Auto  Total Claim Amount
count   1071.000000           1071.000000         1071.000000
mean   39295.701214            193.234360          404.986909
std    30469.427060           1601.190369          293.027260
min        0.000000             61.000000            0.382107
25%    14072.000000             68.000000          202.157702
50%    36234.000000             83.000000          354.729129
75%    64631.000000            109.500000          532.800000
max    99960.000000          35354.000000         2893.239678

summary statistics of categorical columns

In [82]:
cate_stats = {}
for column in categorical_columns:
    cate_stats[column] = categorical_columns[column].value_counts()
    print(column)
print("\n", cate_stats)

ST
GENDER
Education
Policy Type
Vehicle Class

 {'ST': ST
Oregon        320
California    211
Arizona       186
Cali          120
Nevada         98
Washington     81
WA             30
AZ             25
Name: count, dtype: int64, 'GENDER': GENDER
F         457
M         413
Male       39
female     28
Femal      17
Name: count, dtype: int64, 'Education': Education
Bachelor                324
College                 313
High School or Below    296
Master                   94
Doctor                   37
Bachelors                 7
Name: count, dtype: int64, 'Policy Type': Policy Type
Personal Auto     780
Corporate Auto    234
Special Auto       57
Name: count, dtype: int64, 'Vehicle Class': Vehicle Class
Four-Door Car    576
Two-Door Car     205
SUV              199
Sports Car        57
Luxury SUV        20
Luxury Car        14
Name: count, dtype: int64}

## Challenge 2: analyzing the data

### Exercise 1

The marketing team wants to know the top 5 less common customer locations. Create a pandas Series object that contains the customer locations and their frequencies, and then retrieve the top 5 less common locations in ascending order.

In [83]:
dataframe

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
4003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [85]:
locations = dataframe["ST"].value_counts()
print (locations)

ST
Oregon        320
California    211
Arizona       186
Cali          120
Nevada         98
Washington     81
WA             30
AZ             25
Name: count, dtype: int64

In [86]:
locations.sort_values(ascending=True)

ST
AZ             25
WA             30
Washington     81
Nevada         98
Cali          120
Arizona       186
California    211
Oregon        320
Name: count, dtype: int64

In [91]:
less_common_locations = locations[locations < 186].sort_values(ascending=True)
print (less_common_locations)

ST
AZ             25
WA             30
Washington     81
Nevada         98
Cali          120
Name: count, dtype: int64

### Exercise 2

The sales team wants to know the total number of policies sold for each type of policy. Create a pandas Series object that contains the policy types and their total number of policies sold, and then retrieve the policy type with the highest number of policies sold.

*Hint:*
- *Using value_counts() method simplifies this analysis.*
- *Futhermore, there is a method that returns the index of the maximum value in a column or row.*

In [92]:
number_of_policies = dataframe["Policy Type"].value_counts()
print(number_of_policies)

Policy Type
Personal Auto     780
Corporate Auto    234
Special Auto       57
Name: count, dtype: int64

In [95]:
highest_policy = number_of_policies.idxmax()
print(highest_policy)

Personal Auto

### Exercise 3

The sales team wants to know if customers with Personal Auto have a lower income than those with Corporate Auto. How does the average income compare between the two policy types?

- Use *loc* to create two dataframes: one containing only Personal Auto policies and one containing only Corporate Auto policies.
- Calculate the average income for each policy.
- Print the results.

In [97]:
personal_auto = dataframe.loc[dataframe["Policy Type"] == "Personal Auto"]
display(personal_auto)

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
5,OC83172,Oregon,F,Bachelor,825629.78%,62902.0,69.0,1/0/00,Personal Auto,Two-Door Car,159.383042
...,...,...,...,...,...,...,...,...,...,...,...
1065,XD85577,Cali,M,Bachelor,284226.69%,69417.0,73.0,1/1/00,Personal Auto,Four-Door Car,30.874869
1066,TM65736,Oregon,M,Master,305955.03%,38644.0,78.0,1/1/00,Personal Auto,Four-Door Car,361.455219
1067,VJ51327,Cali,F,High School or Below,2031499.76%,63209.0,102.0,1/2/00,Personal Auto,SUV,207.320041
1068,GS98873,Arizona,F,Bachelor,323912.47%,16061.0,88.0,1/0/00,Personal Auto,Four-Door Car,633.600000
1070,MY31220,California,F,College,899704.02%,54230.0,112.0,1/0/00,Personal Auto,Two-Door Car,537.600000

In [100]:
average_income_personalauto = personal_auto["Income"].mean()
print(average_income_personalauto)

38180.69871794872

In [98]:
corporate_auto = dataframe.loc[dataframe["Policy Type"] == "Corporate Auto"]
display(corporate_auto)

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
6,XZ87318,Oregon,F,College,538089.86%,55350.0,67.0,1/0/00,Corporate Auto,Four-Door Car,321.600000
7,CF85061,Arizona,M,Master,721610.03%,0.0,101.0,1/0/00,Corporate Auto,Four-Door Car,363.029680
8,DY87989,Oregon,M,Bachelor,2412750.40%,14072.0,71.0,1/0/00,Corporate Auto,Four-Door Car,511.200000
12,DP39365,California,NaN,Master,879879.70%,77026.0,110.0,1/2/00,Corporate Auto,Four-Door Car,472.029737
...,...,...,...,...,...,...,...,...,...,...,...
1045,WZ31900,Oregon,F,Bachelor,864970.06%,94389.0,107.0,1/0/00,Corporate Auto,SUV,85.063708
1050,BJ53923,Arizona,M,High School or Below,260027.21%,51978.0,66.0,1/0/00,Corporate Auto,Four-Door Car,144.782152
1052,FB23788,Oregon,M,High School or Below,882883.50%,86721.0,111.0,1/0/00,Corporate Auto,SUV,532.800000
1056,PI47776,Oregon,F,Bachelor,253070.51%,89451.0,63.0,1/0/00,Corporate Auto,Four-Door Car,61.769564
1059,YG44474,Oregon,M,College,1401472.13%,54193.0,117.0,1/0/00,Corporate Auto,SUV,720.752945

In [ ]:
corporate_auto.Income.dtype # want to know the dtype of the income column before i do the mean statistics on it

dtype('float64')

In [101]:
average_income_corporateauto = corporate_auto["Income"].mean()
print(average_income_corporateauto)

41390.31196581197

### Bonus: Exercise 4

Your goal is to identify customers with a high policy claim amount.

Instructions:

- Review again the statistics for total claim amount to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount data.

*Note: When analyzing data, we often want to focus on certain groups of values to gain insights. Percentiles are a useful tool to help us define these groups. A percentile is a measure that tells us what percentage of values in a dataset are below a certain value. For example, the 75th percentile represents the value below which 75% of the data falls. Similarly, the 25th percentile represents the value below which 25% of the data falls. When we talk about the top 25%, we are referring to the values that fall above the 75th percentile, which represent the top quarter of the data. On the other hand, when we talk about the bottom 25%, we are referring to the values that fall below the 25th percentile, which represent the bottom quarter of the data. By focusing on these groups, we can identify patterns and trends that may be useful for making decisions and taking action.*

*Hint: look for a method that gives you the percentile or quantile 0.75 and 0.25 for a Pandas Series.*

*Hint 2: check `Boolean selection according to the values of a single column` in https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9*

In [ ]:
total_claim_amount = dataframe["Total Claim Amount"] # selection of the total claim amount column
display (total_claim_amount)

0          2.704934
1       1131.464935
2        566.472247
3        529.881344
4         17.269323
           ...
4003            NaN
4004            NaN
4005            NaN
4006            NaN
4007            NaN
Name: Total Claim Amount, Length: 4008, dtype: float64

In [ ]:
total_claim_statistics = total_claim_amount.describe() #getting to know the statistics of the column
print(total_claim_statistics)

count    1071.000000
mean      404.986909
std       293.027260
min         0.382107
25%       202.157702
50%       354.729129
75%       532.800000
max      2893.239678
Name: Total Claim Amount, dtype: float64

In [ ]:
threshold = total_claim_amount.quantile(0.75) # finding the percentile for the amount at 75% though the statistics also provides same result
print (threshold)

532.8

In [112]:
customers_hightotalclaim = dataframe.loc[dataframe["Total Claim Amount"] > threshold, ["Customer", "ST", "Total Claim Amount"]] #using the threshold as a yardstick to retrieve customers whose total claim is above the 75% range.
display(customers_hightotalclaim)

     Customer          ST  Total Claim Amount
1     QZ44356     Arizona         1131.464935
2     AI49188      Nevada          566.472247
17    OE15005        Cali          647.442031
23    TZ98966      Nevada          554.376763
26    US89481  California          799.200000
...       ...         ...                 ...
1059  YG44474      Oregon          720.752945
1061  RY92647        Cali          546.524896
1068  GS98873     Arizona          633.600000
1069  CW49887  California          547.200000
1070  MY31220  California          537.600000

[264 rows x 3 columns]